### ISSUE TITLE
I wrote a COW implementation in c#!

### ISSUE THREAD

**Issue by moolicc** [BigZaphod/COW#3]
Just wanted to let you know that even more than 15 years after you wrote the first COW implementation, somebody still came across it and thought it would be fun to implement (and it was, of course!).

So essentially, while everybody else writes their own BrainF*ck interpreters for fun, I branched off and wrote a COW interpreter instead.

Thanks!

**Comment by BigZaphod** [comment]
Woo hooooo!

Or should I say..

Moo mooooo!
